name: Check URLs

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "README.md, index.md, about.md, brand.md, faq.md"
          
