name: Greet new contributor

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to the Mentored Sprints website repository! We are so glad that you have decided to contribute. As a reminder we have a [Code of Conduct]() and [Contributing guidelines](https://github.com/pycon-mentored-sprints/mentored-sprints.dev/blob/master/CONTRIBUTING.md)."
          pr-message: "Welcome to the Mentored Sprints website repository! We are so glad that you have decided to contribute. As a reminder we have a [Code of Conduct]() and [Contributing guidelines](https://github.com/pycon-mentored-sprints/mentored-sprints.dev/blob/master/CONTRIBUTING.md)."
